services:
  redroid:
    image: redroid/redroid:11.0.0-latest
    privileged: true
    ports:
      - "5555:5555"
    volumes:
      - redroid-data:/data
    command:
      - androidboot.hardware=redroid
      - androidboot.redroid_width=1080
      - androidboot.redroid_height=1920
      - androidboot.redroid_dpi=280

volumes:
  redroid-data:
